package com.my.website.service;


import java.util.List;

import com.my.website.entity.User;

/**
 * 
 * @author LuHongGang
 * @date 2017年5月5日
 * @time 下午1:46:10
 * @since 1.0
 */
public interface UserService {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_test
     *
     * @mbg.generated
     */
    int insert(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_test
     *
     * @mbg.generated
     */
    List<User> selectAll();


    List<User> selectByCondition(String userName);
}
