package com.my.website.dao;

import org.apache.ibatis.annotations.Param;

import com.my.website.entity.User;

import java.util.List;

public interface UserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbg.generated
     */
    int insert(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbg.generated
     */
    List<User> selectAll();


    List<User> selectByCondition(@Param("userName") String userName);
}